export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USER = "RETRIEVE_USER";
export const EDIT_USER = "EDIT_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_ALL_USER = "DELETE_ALL_USER";

export const CREATE_KENDARAAN = "CREATE_KENDARAAN";
export const RETRIEVE_KENDARAAN = "RETRIEVE_KENDARAAN";
export const EDIT_KENDARAAN = "EDIT_KENDARAAN";
export const UPDATE_KENDARAAN = "UPDATE_KENDARAAN";
export const DELETE_KENDARAAN = "DELETE_KENDARAAN";
export const DELETE_ALL_KENDARAAN = "DELETE_ALL_KENDARAAN";

export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const RETRIEVE_CUSTOMER = "RETRIEVE_CUSTOMER";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_ALL_CUSTOMER = "DELETE_ALL_CUSTOMER";

export const CREATE_TELI = "CREATE_TELI";
export const RETRIEVE_TELI = "RETRIEVE_TELI";
export const EDIT_TELI = "EDIT_TELI";
export const UPDATE_TELI = "UPDATE_TELI";
export const DELETE_TELI = "DELETE_TELI";
export const DELETE_ALL_TELI = "DELETE_ALL_TELI";
export const DELETE_COUNT = "DELETE_COUNT";

export const CREATE_GRADING = "CREATE_GRADING";
export const RETRIEVE_GRADING = "RETRIEVE_GRADING";
export const EDIT_GRADING = "EDIT_GRADING";
export const UPDATE_GRADING = "UPDATE_GRADING";
export const DELETE_GRADING = "DELETE_GRADING";

export const CREATE_PENGANGKUTAN = "CREATE_PENGANGKUTAN";
export const EDIT_PENGANGKUTAN = "EDIT_PENGANGKUTAN";
export const RETRIEVE_PENGANGKUTAN = "RETRIEVE_PENGANGKUTAN";
export const UPDATE_PENGANGKUTAN = "UPDATE_PENGANGKUTAN";
export const DELETE_PENGANGKUTAN = "DELETE_PENGANGKUTAN";
export const DELETE_ALL_PENGANGKUTAN = "DELETE_ALL_PENGANGKUTAN";

export const CREATE_PENGIRIMAN = "CREATE_PENGIRIMAN";
export const EDIT_PENGIRIMAN = "EDIT_PENGIRIMAN";
export const MODIFY_PENGIRIMAN = "MODIFY_PENGIRIMAN";
export const RETRIEVE_PENGIRIMAN = "RETRIEVE_PENGIRIMAN";
export const UPDATE_PENGIRIMAN = "UPDATE_PENGIRIMAN";
export const DELETE_PENGIRIMAN = "DELETE_PENGIRIMAN";
export const DELETE_ALL_PENGIRIMAN = "DELETE_ALL_PENGIRIMAN";
export const EXPORT_DATA_PENGIRIMAN = "EXPORT_DATA_PENGIRIMAN";
export const GET_DASHBOARD = "GET_DASHBOARD";

export const CREATE_PRODUKSI = "CREATE_PRODUKSI";
export const EDIT_PRODUKSI = "EDIT_PRODUKSI";
export const RETRIEVE_PRODUKSI = "RETRIEVE_PRODUKSI";
export const UPDATE_PRODUKSI = "UPDATE_PRODUKSI";
export const DELETE_PRODUKSI = "DELETE_PRODUKSI";
export const DELETE_ALL_PRODUKSI = "DELETE_ALL_PRODUKSI";